server:
  port: 8089

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fonteditor?characterEncoding=utf-8
  mail:
    host: smtp.163.com
    username: d1534400213@163.com
    password: KINSWSHWIJWOKYGN
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          socketFactory.port: 465
          socketFactory.fallback: false
          ssl.enable: false
logging:
  level:
    com.brthree: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto